### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by mdugot42** [Liliaze/GOMOKU#10]
Ajouter multithreading dans la fonction startMinMax.

**Comment by Liliaze** [comment]
Tu as fais un commit dans ce sens, est-ce-que tu pense l'avoir complétement finit ? Si oui à fermer. Et du coup est-ce-que sans les DEBUG on tient en moins de 10s ? J'ajoute le timer à mon prochain commit dans ce sens.

**Comment by mdugot42** [comment]
Il y a peut-être encore moyen d'optimiser le min-max mais le multithreading de son coté semble fonctionner. Je ferme.
