### ISSUE TITLE
Interface graphique

### ISSUE THREAD

**Issue by Liliaze** [Liliaze/GOMOKU#2]
SFML ou GTK+
Faire Makefile correspondant

**Comment by Liliaze** [comment]
Installer l'environnement en conséquence

**Comment by Liliaze** [comment]
interface commencé avec la SFML.

**Comment by Liliaze** [comment]
La SFML est bien installé sur nos pc et sur les macs de l'école. Le Makefile a bien été mise à jour en conséquence.

**Comment by Liliaze** [comment]
Pour l'instant on a une première version avec le plateau de jeu sur lequel on peux poser les pierres noirs ou blanches. Reste à : 
- Ajouter sur l'écran de jeu : ZONES DE CAPTURE + TIMER IA + COUNT TOUR DE JEU + Identification couleur des joueurs.
- CREER LES AUTRES ECRANS selon le state : welcome, menu, victoire / defaite, again, goodbye.

**Comment by mdugot42** [comment]
- Si ce n'est pas trop compliqué, ça serait peut-être bien d'ajouter une prévisualisation semi-transparente d'où la pierre va se poser selon la position du curseur (un peu comme sur ce site : [http://gomoku.yjyao.com/](http://gomoku.yjyao.com/)).

- Réduire la taille de la fenêtre.

**Comment by mdugot42** [comment]
Fermeture après séparation en plusieurs issues.
