### ISSUE TITLE
Implementer les conditions de victoire / defaite

### ISSUE THREAD

**Issue by Liliaze** [Liliaze/GOMOKU#5]
Alignement 5 pions ou plus
- si pas de possibilité adversaire de casser l'alignement par capture
- ou si l'adversaire a déjà 4 pairs capturé... ? A verif
Capture 10 pions (5 capture)

**Comment by Liliaze** [comment]
Tu as bien fait l'alignement des 5 pierres cela fonctionne, je vais faire la zone de capture des pierres et ajouter la règle correspondante.
Penser à vérifier quand même, j'ai un doute si la rêgle d'alignement a besoin d'autres précisions. Il me semble qu'avant d'accorder la victoire il faut vérifier si l'adversaire ne peux pas faire une ultime capture... A vérifier.

**Comment by Liliaze** [comment]
Pour moi cette issue est également à fermer depuis que tu as ajouté le check de capture avant la confirmation d'un alignement de 5. Qu'en dis-tu ?

**Comment by mdugot42** [comment]
Normalement ça marche. Je ferme.
