### ISSUE TITLE
IA avec le min max en solo

### ISSUE THREAD

**Issue by Liliaze** [Liliaze/GOMOKU#6]

**Comment by Liliaze** [comment]
L'IA est invinsible

**Comment by Liliaze** [comment]
Profondeur 10
Moins de 10s
Threading ?

**Comment by mdugot42** [comment]
Fermeture après création de nouvelles issues :

- Multithreading et optimisation

- Prise en compte des captures

- Prise en compte du double three

- Prise en compte des conditions de victoire demandées par le sujet
